//
//  Logos.swift
//  LoginKeeper
//
//  Created by Dusan Juranovic on 12/17/17.
//  Copyright © 2017 Dusan Juranovic. All rights reserved.
//

import Foundation

var logoImagesPNG = ["pngloginkeeper","png1password","png9gag","pngaddress","pngadidas","pngairplane","pngalfaromeo","pngamazon","pngandroid","pnganonymous","pngapple","pngapplepay","pngappletv","pngappstore","pngaudacity","pngaudi","pngautocad","pngbank","pngbbc","pngbing","pngbitbucket","pngbitcoin","pngblogger","pngcalendar","pngcamera","pngchevron","pngchrome","pngconference","pngcontact","pngcreditcard","pngcreditcardamericanexpress","pngcreditcarddinersclub","pngcreditcarddiscover","pngcreditcardmaestro","pngcreditcardmaster","pngcreditcardvisa","pngcydia","pngdebian","pngdell","pngdigg","pngdocker","pngdocument","pngdota","pngdropbox","pngdvd","pngebay","pngemail","pngfacebook","pngfacebookmessenger","pngferrari","pngfingerprint","pngfirefox","pngfitbit","pngfoursquare","pnggame","pnggithub","pnggitter","pnggmail","pnggoogle","pnggoogleearth","pnggoogleplus","pnggoogletranslate","pnggta","pnghbogo","pnghome","pnghp","pnghulu","pngicons8","pngicq","pnginstagram","pnginstapaper","pnginternetexplorer","pngios","pngitunes","pngjava","pngjenkins","pngjodel","pngjoomla","pngkey","pngkikmessenger","pngkodi","pnglamborghini","pnglego","pnglike","pngline","pnglinkedin","pnglinux","pnglock","pnglogin","pnglogin2","pnglogout","pnglol","pngmac","pngmicrosoftwindows","pngminecraft","pngmyspace","pngnetflix","pngnike","pngok","pngonlinesupport","pngopenstack","pngopera","pngoracle","pngpaypal","pngpercentage","pngpersonman","pngpersonwoman","pngphp","pngpiedpiper","pngpinterest","pngpirates","pngpixarlamp","pngplaystation","pngpricetag","pngpricetagdollar","pngpricetagpound","pngqq","pngquora","pngreactnative","pngrealmadrid","pngreddit","pngrestaurant","pngrollsroyce","pngshowtime","pngsiri","pngskype","pngslack","pngsnapchat","pngsoundcloud","pngspider","pngspotify","pngstackoverflow","pngstarwars","pngsteam","pngstrava","pngstumbleupon","pngsubaru","pngswift","pngsystem","pngtesla","pngtodolist","pngtripadvisor","pngtumblr","pngtv","pngtwitter","pnguber","pngunity5","pngunrealengine","pnguplay","pnguser","pngutorrent","pngvimeo","pngvirtualbox","pngvkontakte","pngvlc","pngwallet","pngwalmart","pngwechat","pngweibo","pngwhatsapp","pngwifi","pngwii","pngwordpress","pngwork","pngwww","pngxbox","pngxing","pngyahoo","pngyelp","pngyoutube","pngzuma",]

let accountLogos = ["admob", "adsense", "adwords", "agoda", "aib", "airbnb", "alibaba", "aliexpress", "amazon","aol", "apple", "appstore", "badoo", "baidu", "balkaniyum", "bbc", "bing", "bitbucket", "blogger", "booking", "cheapflights", "classmates", "cleartrip", "codewars", "couchsurfing", "crunchyroll", "dailymotion", "dropbox", "duolingo", "ebay", "emirates", "etoro", "facebook", "firebase", "flickr", "flightaware", "flixster", "foursquare", "friendster", "github", "gmail", "google+", "google", "grindr", "hostel", "instagram", "line", "linkedin", "mashreq", "meetup", "microsoft", "msn", "mts", "myheritage", "myspace", "mytaxi", "nbd", "netflix", "openstreetmaps", "opera", "orkut", "otel", "overpass", "pinterest", "qq", "quora", "qzone", "reddit", "renren", "ryanair", "shazam", "skype", "skyscanner", "slack", "snapchat", "soundcloud", "soundhound", "stackoverflow", "stumbleupon","swift", "tagged", "taringa", "telegram", "telenor", "thedots", "tinder", "treehouse", "trello", "tripadvisor", "triposo" ,"tumblr", "twitter", "uber", "upwork", "vevo", "viber", "vimeo", "vine", "vip", "vkontakte", "wechat", "weibo", "whatsapp", "wikipedia", "yahoo", "yelp", "youtube", "yy"]
